kind: Service
apiVersion: v1
metadata:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.0.1
    k8sapp: cart
    expose: "true"
  name: cart
  namespace: {NAMESPACE}
  annotations:
    config.xposer.stakater.com/Domain: stakater.com
    config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-{{.Namespace}}'
    config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Domain}}'
    xposer.stakater.com/annotations: |-
      kubernetes.io/ingress.class: external-ingress
      ingress.kubernetes.io/force-ssl-redirect: true
spec:
  selector:
    app: cart
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080